apiVersion: v1
kind: Pod

metadata:
  name: mlapp-pod
  labels:
    app: mlapp

spec:
  containers:
    - name: mlapp-container
      image: auduj01/mlapp:latest
      ports:
      - containerPort: 5000